### ISSUE TITLE
weez: fill in your part in the index page

### ISSUE THREAD

**Issue by RH-sdavey** [RH-sdavey/sean-helper#7]
converted this from a note to an issue for weezy ⭐️ 

edit the code in 'content/index.mdx'
follow my example ( but my formatting is a bit fucked to be honest) of how to make a 'blockquote'
start your line with > 
and write some text about what happened when we met and how you got into IT and where from. :trollface: 

to be honest, you dont need my approval, :rage2:  you can just squash and merge without me... but make sure its def. right if you do that.... 😖 

remember to include the projct in your PR, as that will automate the kanban ticket movement.
and... at the top of this page there is a button called 'wiki' I think we should start that for you to make notes and FAQ... Ill create another issue for that 😉 
good luck man 🙏 and dont 😲 if you get stuck ... ❓ 
💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩 💩

**Comment by Salloweezy** [comment]
Added profile paragraph into index.mdx
